# -*- coding: utf-8 -*-
"""Training_v1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yGl9JCaeWUpV3uwyUiUN3LrYxXidCo9F
"""

from google.colab import drive
drive.mount('/content/drive')

!ls /content/drive/MyDrive

!unzip /content/drive/MyDrive/data.zip -d /content/datasets/

!pip install ultralytics

import torch
print("GPU disponible:", torch.cuda.is_available())
print("Cantidad GPUs:", torch.cuda.device_count())
if torch.cuda.is_available():
    print("Nombre GPU:", torch.cuda.get_device_name(0))

!ls /content/datasets/data/

import yaml

yaml_path = "/content/datasets/data/strawberries.yaml"

with open(yaml_path, 'r') as f:
    data = yaml.safe_load(f)

# Actualizamos las rutas de acuerdo a la nueva estructura
data['train'] = "/content/datasets/data/images/train"
data['val']   = "/content/datasets/data/images/val"
# Si no tienes folder 'test', puedes dejarlo como vacío o eliminar la línea
# data['test']  = "/content/datasets/data/images/test"  # solo si existe

# Guardamos los cambios
with open(yaml_path, 'w') as f:
    yaml.dump(data, f)

!cat /content/datasets/data/strawberries.yaml

from ultralytics import YOLO

model = YOLO("yolov8n.pt")

model.train(
    data="/content/datasets/data/strawberries.yaml",
    epochs=50,
    imgsz=640,
    batch=16,
    name="strawberry_exp"
)

metrics = model.val()
print(metrics)

!zip -r runs.zip runs

from google.colab import files
files.download("runs.zip")
files.download("yolo11n.pt")
files.download("yolov8n.pt")