# -*- coding: utf-8 -*-
"""Training_v1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yGl9JCaeWUpV3uwyUiUN3LrYxXidCo9F
"""

!pip install ultralytics

import torch
print("GPU disponible:", torch.cuda.is_available())
print("Cantidad GPUs:", torch.cuda.device_count())
if torch.cuda.is_available():
    print("Nombre GPU:", torch.cuda.get_device_name(0))

!unzip /content/Fucking_Strawberry.v2i.yolov8.zip -d /content/datasets/

!ls /content/datasets

import yaml

yaml_path = "/content/datasets/data.yaml"

with open(yaml_path, 'r') as f:
    data = yaml.safe_load(f)

data['train'] = "/content/datasets/train/images"
data['val']   = "/content/datasets/valid/images"
data['test']  = "/content/datasets/test/images"

with open(yaml_path, 'w') as f:
    yaml.dump(data, f)

!cat /content/datasets/data.yaml

from ultralytics import YOLO

model = YOLO("yolov8n.pt")

model.train(
    data="/content/datasets/data.yaml",
    epochs=50,
    imgsz=640,
    batch=16,
    name="strawberry_exp"
)

metrics = model.val()
print(metrics)